### PR TITLE
closes #136 logo and user guides

### LINKED ISSUE #136: Documentation:  Use User Guides instead of Articles for site
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

Use User Guides instead of Articles for site in top bar, and update so that admiralonco logo is shown in browser, instead of admiral.

### PR DESCRIPTION
**Pull request by rossfarrugia**
Closes #136 .

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md`
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiralonco/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done!  Much love to your accomplishment!

### CODE REVIEW

**Comment by rossfarrugia** [comment]
@bms63 did i get the favicon bits right as you were explaining at the call earlier? i ran `build_favicons()` from pkgdown. i didn't find anywhere i needed to add anything more in `_pkgdown.yml` for the logo bit though. if i missed anything please comment and maybe @bundfussr could fix whilst i'm out of office this week.

**Comment by bms63** [comment]
This renders for me as the onco hex image.  I found that after the favicons update, I had to clear browser and restart the session to get admiraldev hex to appear.   It all looks good to me.
image

**Comment by bms63** [comment]
Did you guys mean to have both of those hex stickers on the same page?

**Comment by rossfarrugia** [comment]
@bms63 i don't think that was intentional no - if it's an easy fix let us know!

**Comment by bms63** [comment]
These are comparing the READMEs for admiral and admiralonco.  You just need to move the img stuff up to the next line.

image

**Pull request merged**
