### PR TITLE
closes #160_crandate updated

### PR DESCRIPTION
**Pull request by HinalPat**
_pkgdown.yml program updated : cran date from false to true & correct indention of 'news'

Please add "Closes #<issue number>" to the title of the pull request. Then the
issue is closed automatically once it is merged to `main`.

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md`
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiralonco/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x ] Link the issue so that it closes after successful merging. 
- [x ] Address all merge conflicts and resolve appropriately 
- [x ] Pat yourself on the back for a job well done!  Much love to your accomplishment!

The following line requests to update the man pages by the "Man Pages" workflow.

/roxygenize

### CODE REVIEW

**Comment by rossfarrugia** [comment]
@HinalPat few quick things i spotted:
- change it so you're merging into `devel` branch not `main` - `main` is only for releases
- add the "closes #" in the PR title before the issue number and this means the issue will auto-close when this later gets merged to `main` as part of the release
- on RHS under development link issue 160

I'll double check the actual update later and let you know if i spot anything

**Comment by HinalPat** [comment]
@rossfarrugia how did I manage not to follow the the guidance! Updated now!

**Comment by rossfarrugia** [comment]
@HinalPat everybody does this their first contribution don't worry :) i probably did it 2 or 3 times...

**Review by rossfarrugia — APPROVED** [review]

**Comment by rossfarrugia** [comment]
@HinalPat first PR successfully merged 🏅

**Pull request merged**
