### PR TITLE
closes #203 adtte clean ups in line with admiral

### LINKED ISSUE #203: ADTTE template update after derive_param_tte() updated
See https://github.com/pharmaverse/admiral/issues/1576
As this is now updated, impact will be we can remove lines like `adrs = filter(adrs_resp, !is.na(TEMP_RESPDT))` in our template which will now become redundant for each of the duration of response parameters.

### PR DESCRIPTION
**Pull request by rossfarrugia**
Please add "Closes #<issue number>" to the title of the pull request. Then the
issue is closed automatically once it is merged to `main`.

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md`
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiralonco/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done!  Much love to your accomplishment!

The following line requests to update the man pages by the "Man Pages" workflow.

/roxygenize

### CODE REVIEW

**Comment by rossfarrugia** [comment]
@bundfussr was going to wait til the workflows run but they'll fail anyway until https://github.com/pharmaverse/admiralonco/pull/194 is merged, so feel free to review this anytime.

**Review by bundfussr — APPROVED** [review]

**Comment by rossfarrugia** [comment]
@bundfussr i noticed the spell check workflow failed. i remember hearing some updates here to the wordlists, but dont remember the exact details. want me to update the wordlist in this PR or is it already being taken care of elsewhere?

**Comment by bundfussr** [comment]
> @bundfussr i noticed the spell check workflow failed. i remember hearing some updates here to the wordlists, but dont remember the exact details. want me to update the wordlist in this PR or is it already being taken care of elsewhere?

@rossfarrugia , I did some fixes in https://github.com/pharmaverse/admiralonco/pull/194/files#diff-735340626a484475fb3abdf013331613f4b7fbf657a918c4f35d6a7bedc7766b. This should solve the issue. So no need to do anything in this PR (unless I missed something).

**Comment by rossfarrugia** [comment]
thanks Stefan - looks good to me!

**Pull request merged**
